pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'python3 -m pip install -r my-tests/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest my-tests/tests/ --tb=short'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
        failure {
            echo 'Tests failed!'
        }
    }
}
